### ISSUE TITLE
How to deploy multiple functions to same Azure Function App using Azure Pipelines?

### ISSUE THREAD

**Issue by StefH** [Azure/Azure-Functions#1106]
I have a solution in Visual Studio defining two functions : **Function1** and **Function2**.

I use the Azure DevOps `pipelines.yml` file to build a publish these two Azure Functions. So the artifact contains two zip files : **Function1.zip** and **Function2.zip**

In the release pipeline I use two tasks (both a `Azure App Service Deploy (Preview) v4`).

The first task deploys **Function1**:
![image](https://user-images.githubusercontent.com/249938/50995886-bf0dcc00-1520-11e9-8e6a-d537879616fc.png)

And the second task deploys **Function2**:
![image](https://user-images.githubusercontent.com/249938/50995957-f4b2b500-1520-11e9-8809-993d7171f67b.png)

The problem is that after running these two steps, all existing Functions running at "App Service A" are removed and only **Function2** is defined and running?

Is my scenario not supported? And should I use a different approach?

This question is also related to https://github.com/Azure/Azure-Functions/issues/971, but the answer provided there is not correct for my problem.

**Comment by JohnReeson** [comment]
Is there any reason that you deploy those two functions separately?  We could put two functions in the same project and deploy together.

Check the [wiki](https://github.com/Azure/Azure-Functions/wiki/Deploying-Function-Apps-vs-individual-Functions).

>the unit of deployment should be the Function App, and not individual functions.

**Comment by StefH** [comment]
I wanted to structure the project in a more logical way. I did solve my issue by implementing the following structure:

``` C#
|
+ AzureFunctions.Common
|
+ Function1.Library
+ Function1.BusinessLogic
|
+ Function2.Library
+ Function2.BusinessLogic
|
+ AzureFunctions // This is the main project which references Function1.Library & Function2.Library
```

What I noticed is if I did define the real function:
``` c#
[FunctionName("Function1")]
public static async Task<IActionResult> Run([HttpTrigger(AuthorizationLevel.Function, "POST")] HttpRequest req, ILogger log)
```
inside the **Function1.Library** project, it was `not` found by the main project (AzureFunctions)?

So now I ended up with adding the real functions in the main project (AzureFunctions).

@JohnReeson Do you have an explanation for this?

**Comment by JohnReeson** [comment]
`function.json` (containing trigger definition) are not copied to the main project, it's by design that how Function SDK build the code. Check [this issue](https://github.com/Azure/azure-functions-host/issues/2836) for more details.

**Comment by StefH** [comment]
I see.
And actually `function.json` is generated by the SDK, so no way to manually update this.

**Comment by JohnReeson** [comment]
Yeah, there's an [issue](https://github.com/Azure/azure-functions-vs-build-sdk/issues/202) tracking this requirement to build SDK, so you may close this one?

**Comment by StefH** [comment]
yes. Thanks for your support.

**Comment by szferle** [comment]
Hi All,
Was the original question answered?
I am also trying to deploy two zipped Functions to the same Azure Function App, same result: the first one gets deployed than replaced with the second one.
I have these tasks in the yaml:
```
          - task: AzureRmWebAppDeployment@4
            displayName: Deploy '$(WebAppName)'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'x'
              appType: 'functionApp'
              WebAppName: '$(WebAppName)'
              packageForLinux: '$(Pipeline.Workspace)/drop/$(FuncName1).zip'
              enableCustomDeployment: true
              DeploymentType: 'zipDeploy'

          - task: AzureRmWebAppDeployment@4
            displayName: Deploy '$(WebAppName)'
            inputs:
              ConnectionType: 'AzureRM'
              azureSubscription: 'x'
              appType: 'functionApp'
              WebAppName: '$(WebAppName)'
              packageForLinux: '$(Pipeline.Workspace)/drop/$(FuncName2).zip'
              enableCustomDeployment: true
              DeploymentType: 'zipDeploy'
```
