### ISSUE TITLE
Azure queue trigger function on AKS not starting

### ISSUE THREAD

**Issue by JK87iab** [Azure/Azure-Functions#1497]
Hi,
deploying azure functions to AKS. HTTP Trigger works fine. Local testing of my queue trigger works fine too.

Once deployed I see 0 pods created and messages are stuck in the queue

```
NAME                READY   UP-TO-DATE   AVAILABLE   AGE
myfunctionproject   0/0     0            0           34m
```

My deployment file.
```

data:
  FUNCTIONS_WORKER_RUNTIME: cHl0aG9u
  AzureWebJobsStorage: KEY TO STORAGE
apiVersion: v1
kind: Secret
metadata:
  name: myfunctionproject
  namespace: default
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: myfunctionproject
  namespace: default
  labels:
    app: myfunctionproject
spec:
  selector:
    matchLabels:
      app: myfunctionproject
  template:
    metadata:
      labels:
        app: myfunctionproject
    spec:
      containers:
      - name: myfunctionproject
        image: cpgaikn.azurecr.io/myfunctionproject
        env:
        - name: AzureFunctionsJobHost__functions__0
          value: QueueTrigger
        envFrom:
        - secretRef:
            name: myfunctionproject
      imagePullSecrets:
      - name: kn-secret
---
apiVersion: keda.k8s.io/v1alpha1
kind: ScaledObject
metadata:
  name: myfunctionproject
  namespace: default
  labels:
    deploymentName: myfunctionproject
spec:
  scaleTargetRef:
    deploymentName: myfunctionproject
  triggers:
  - type: azure-queue
    metadata:
      name: msg
      type: queueTrigger
      direction: in
      queueName: optimizer-v2-kn
      connection: AzureWebJobsStorage
---
```

Any other way to debug why no pods are getting created? Using an acr + a secret I created
