### ISSUE TITLE
Unreasonably high storage transaction activity (GetBlobProperties) causing increased cost of running Functions

### ISSUE THREAD

**Issue by mkieres** [Azure/Azure-Functions#2417]
I am running into the same issue as described in #2231, where my functions are generating some ridiculous and unexplained storage activity causing the cost of running functions to increase - more details below. It's worth noting that there were quite a few other similar issues raised in this repo (#2138, #1307, #832), so the problem is not necessarily new.

I also made a [comment](https://github.com/Azure/Azure-Functions/issues/2231#issuecomment-1772518721) in one #2231 but it didn't get any traction for a week so I decided to create a new issue, hoping that someone will have a look at this.

To set the context, I have a single .NET 7 Linux Azure Function v4 running on a consumption plan with a queue trigger. It's an open source project so the function code can be found [here](https://github.com/Progrunning/BoardGamesCompanion/tree/main/backend/BGC.Functions). As others who experienced this issue, I essentially have noticed that my bills were growing unexpectedly, which lead me to review where the cost is coming from. For some completely unknown reason to me I found out that there is close to ~700k `GetBlobProperties` operations happening in the storage over the span of a day.

![image](https://github.com/Azure/Azure-Functions/assets/8372764/d3def10e-1d2d-49b5-8cbe-d935affea68c)

To my huge disappointment, there doesn't seem to be a proper solution to fix this issue and neither there is a documentation to understand why the operations number is so high and how to control/reduce it. I browsed around and found a few "hacks" that allegedly helped others reduce numbers of operations and brought the cost of the storage down. Namely I have done the following:

- Downgraded v2 storage to legacy v1 as per recommendation by @nzthiago ([comment](https://github.com/Azure/Azure-Functions/issues/2231#issuecomment-1172644647))
- Deleted the `AzureWebJobsDashboard ` from the configuration ([SO comment](https://stackoverflow.com/a/60115446/510627))
- Ensured that I don't have this line `.AddJsonFile("local.settings.json", optional: true, reloadOnChange: true)` in the config code ([SO comment](https://stackoverflow.com/a/61259940/510627))
- Switched from Zip Deploy to Zip Deploy to Run With Package ([docs](https://learn.microsoft.com/en-us/azure/azure-functions/run-functions-from-deployment-package#enable-functions-to-run-from-a-package)) as [per this comment](https://github.com/Azure/Azure-Functions/issues/2231#issuecomment-1193494111)

Unfortunately none of the above helped. The storage transaction numbers have not dropped one bit. I'm getting really annoyed and helpless. It is frustrating, to say the least, that there is this "hidden" cost of running functions that is not documented anywhere, which misleads developers into thinking that they can run something inexpensively in Azure. It also amazes me that this has not been properly addressed for such a long time - the first comments that I found relating to this issue were made around 2018. That said, I still hope that someone will be able to help me out.

**Comment by bhagyshricompany** [comment]
@fabiocav  pls comment and validate

**Comment by nzthiago** [comment]
Hi Mikolaj - we do have it documented in several areas that a storage account is required and used by Azure Functions. For example:
* [Pricing page](https://azure.microsoft.com/en-us/pricing/details/functions/) has a note "A storage account is created by default with each Functions app. The storage account is not included in the free grant. Standard [storage rates](https://azure.microsoft.com/en-us/pricing/details/storage/files/) and [networking rates](https://azure.microsoft.com/en-us/pricing/details/bandwidth/) charged separately as applicable."
* [This page](https://learn.microsoft.com/en-us/azure/azure-functions/storage-considerations?tabs=azure-cli) regarding storage considerations
* Other related costs documented [here](https://learn.microsoft.com/en-us/azure/azure-functions/functions-consumption-costs?tabs=portal#other-related-costs) that calls out storage account.

So I wouldn't necessarily say that this is hidden and not documented anywhere. But always looking at how we could improve on this. In our backlog for the long run we hope to remove the need for storage account overall for Functions.

As you mentioned on the other thread a support ticket isn't an option for you but please do share that info as per [these instructions](https://github.com/Azure/azure-functions-host/wiki/Sharing-Your-Function-App-name-privately). The steps you followed should have addressed this, so we would need to investigate your app specifically to see if there's any extra issue that your app is running into that's causing increasing storage transactions numbers... I really want to help figure out what is going on with your app as this is not expected, thank you for reporting this and for your patience!

**Comment by mkieres** [comment]
hey @nzthiago, I didn't necessarily mean that the storage part of the costs of running Functions is hidden, as I it is clear from the docs you shared. The "hidden" cost that I was referring to is the undocumented part where the storage activity skyrockets if you don't configure the function in certain way - which also doesn't help in all cases (i.e. mine).

I would be very gratefully if you and/or someone from your team could have a look at what could potentially be wrong with my setup. The function that is causing issues is https://bgc-prod-func.azurewebsites.net - let me know if you need any other information for your investigation. Unsure if this is important for your investigations but the function is stopped atm, to avoid any extra charges caused by the storage activity. I'm happy to turn it on if/when needed. I'm also happy to get on a call to explain the setup/config and update things in Azure, for you to test/verify.

**Comment by nzthiago** [comment]
Hi Mikolaj - apologies, I might need some more folks from the team to help me investigate. In the meantime, if this is viable, I just followed you on twitter in case you can DM me your email address I can help set up a follow up investigation too. Let me know what you prefer, thank you.

**Comment by tim-brand** [comment]
@mkieres @nzthiago Did this got any update? We've experiencing this same issue as well.

**Comment by mkieres** [comment]
hey @tim-brand, @nzthiago got in touch with me via email and was able to ask someone from Azure Functions Team Product Group to look into this problem. Bottom line of our email conversation was, that I was asked to try investigate it myself. Here's a part of the email I got with instructions to isolate the problem:

> Please try to isolate the issue and give us the repro:
>
> 1. Create a simple function app which has a ServiceBus trigger. Test it - I believe you won’t see a lot GetBlobProperties for the storage created for the function app.
> 2. Start adding your stuff to the simple function app and stop when you see GetBlobProperties activity spikes.

It was indicated to me that this is most likely a problem with my function (although I still don't see how it could be because the function is very trivial). Regardless, I have not found time to trial and error this unfortunately. I ended up disabling my function altogether.

**Comment by tim-brand** [comment]
Thanks for the reply @mkieres!
All our functions are using the ServiceBus trigger, so I will try to investigate on our side.
One more question. Are you using durable or non-durable functions? We are using a mix, some are durable, some aren't. I can imagine that the durable functions require more blob IO because of the state storage.

**Comment by mkieres** [comment]
@tim-brand I have only a single function and it's non-durable ([code](https://github.com/Progrunning/BoardGamesCompanion/blob/main/backend/cache/BGC.Functions/Functions/UpdateBoardGameCacheFunction.cs))

**Comment by rebrovoleksii** [comment]
We have similar issue with durable functions. Function itself is a simple HTTP trigger. Under the hood it checks if another instance of orchestrator is already running for given EntityId, if not schedules an orchestrator. Orchestrator simply makes a call to external API.
Here is a graph of metrics - number of requests vs number of GetBlob+GetBlobProperties transactions. Seems like for every function invocations there're 2 transactions to Blob storage.
<img width="1637" alt="Image" src="https://github.com/user-attachments/assets/2aac3636-d96f-4ae1-bc7d-2ef1477d98ff" />
I know that durable functions use blob leases for partitioning but that's looks similar to https://github.com/Azure/azure-functions-durable-extension/issues/2981#issuecomment-2552405572 . We will try to update to latest version of Microsoft.Azure.Functions.Worker.Extensions.DurableTask and check if number of blob transactions is reduced.

**Comment by sparkeros** [comment]
## Solution Found: Disable Oryx Remote Build

We recently debugged a similar issue where deployments were generating **290K+ storage transactions** and causing unexpected costs.

### Root Cause
The `--build-remote true` flag (or Oryx enabled via `scm-do-build-during-deployment`) causes Azure to run `pip install` on the Azure side. Each file operation during pip install generates storage transactions - we measured **20-30K transactions per minute** during the build phase.

### Fix
Build Python dependencies **locally on the GitHub runner** (which is Linux), then deploy with Oryx disabled:

```yaml
jobs:
  build:
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: actions/setup-python@v5
        with:
          python-version: '3.11'
      
      # Install dependencies LOCALLY on GitHub runner
      - name: Install dependencies
        run: |
          pip install -r requirements.txt --target=".python_packages/lib/site-packages"
      
      - name: Create deployment package
        run: zip -r release.zip . -x ".git/*" -x ".venv/*"
      
      - uses: actions/upload-artifact@v4
        with:
          name: python-app
          path: release.zip

  deploy:
    runs-on: ubuntu-latest
    needs: build
    steps:
      - uses: actions/download-artifact@v4
        with:
          name: python-app
      - run: unzip release.zip -d ./deploy
      - uses: azure/login@v2
        with:
          # your credentials
      
      # CRITICAL: Disable Oryx
      - uses: Azure/functions-action@v1
        with:
          app-name: 'MyFunctionApp'
          package: './deploy'
          scm-do-build-during-deployment: false
          enable-oryx-build: false
```

### Results
- Deployment time: **9+ minutes → 2 minutes**
- Storage transactions: **20-30K/minute → <1,000 total**

The key insight is that Ubuntu runners are Linux, same as Azure Functions. Dependencies compiled on Ubuntu work on Azure without Oryx rebuilding them.

Related: https://github.com/Azure/functions-action/issues/294
