### ISSUE TITLE
How to deploy Flex Consumption function from zip file?

### ISSUE THREAD

**Issue by xperiandri** [Azure/Azure-Functions#2496]
There is no documentation at all on how to deploy Flex Consumption from CI.
Can you fill that gap???

**Comment by Juriyx** [comment]
@pragnagopa, @nzthiago, @alexkarcher-msft Could you, please, comment on this?

**Comment by xperiandri** [comment]
We want to deploy them from the Azure DevOps CI pipeline

**Comment by nzthiago** [comment]
Hi @xperiandri - sorry I missed this question. The support for the Functions task for Azure DevOps is still under way, being implemented by @FinVamp1. The current workaround would be to deploy the zip file using the [AZ CLI task](https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-cli-v2?view=azure-pipelines), with the following command:
```
az functionapp deployment source config-zip -g <resourceGroup> -n <functionAppName> --src <pathToZipFile>
```

**Comment by xperiandri** [comment]
It works, thank you very much!

**Comment by nzthiago** [comment]
FYI - Flex Consumption is now supported by the Azure DevOps task. See the `isFlexConsumption` option for the Azure Functions Deploy v2 task https://learn.microsoft.com/en-us/azure/devops/pipelines/tasks/reference/azure-function-app-v2?view=azure-pipelines

**Comment by shubham-cyborg** [comment]
I followed the same steps as mentioned in the docs and added a task in azure pipeline for flex consumption with isFlexConsumption: true. It shows the deploy task as succeeded however the deployment is not done. No functions are being shown in the list on azure function app. 
When i check the logs from azure devops pipeline, it has the following logs:

The Deployment Type option does not apply for Flex Consumption.
Successfully added release annotation to the Application Insight

**Comment by xperiandri** [comment]
Post you task YAML

**Comment by ryanshirley-flipdish** [comment]
I am facing the same issue. This is my YAML.

## AzureFunctionApp@2 deployment

```
- task: AzureFunctionApp@2
            displayName: 'Deploy Function App'
            inputs:
              azureSubscription: ${{ parameters.azureSubscription }}
              appType: 'functionAppLinux'
              isFlexConsumption: true
              appName: ${{ parameters.appName }}
              package: '$(Pipeline.Workspace)/drop/$(Build.BuildId).zip
```

**Error:**
```
Starting: Deploy Function App
==============================================================================
Task         : Azure Functions Deploy
Description  : Update a function app with .NET, Python, JavaScript, PowerShell, Java based web applications
Version      : 2.247.1
Author       : Microsoft Corporation
Help         : https://aka.ms/azurefunctiontroubleshooting
==============================================================================
Got service connection details for Azure App Service:'xxx'
The Deployment Type option does not apply for Flex Consumption.
App Service Application URL: http://xxx.azurewebsites.net/
Finishing: Deploy Function App
```
