### ISSUE TITLE
EventGrid Based Storage Triggers

### ISSUE THREAD

**Issue by derekrprice** [Azure/Azure-Functions#2583]
We have a trigger defined like so, and it works in the Azure Functions in App Service.
```
  "bindings": [
    {
      "name": "myBlob",
      "type": "blobTrigger",
      "direction": "in",
      "path": "log/{customerID}/{unitID}/{fileName}",
      "dataType": "binary",
      "source": "EventGrid",
      "connection": "AzureLogFileStorage"
    },
// ...
}
```

We are having trouble migrating JUST this ONE EventGrid-based trigger.  I can get the new blob event posted to the Azure Functions Runtime container in AKS, but there is nothing listening for it at the path that works in the Azure Functions instance (/runtime/webhooks/blobs).  I am trying to figure out what Functions service normally handles that URL path as I am seeing a 404 from the Functions Runtime container.  The doc on the net is tantalizing but sketchy.  It sounds like a few people have gotten this to work, but they have not provided detailed instructions on how to duplicate the feat.

Can anyone provide any details on making this setup work?  Thanks in advance!

**Comment by JAdluri** [comment]
Hello @derekrprice could you please mention steps to reproduce this issue .

**Comment by derekrprice** [comment]
Hi @JAdluri !  Here's the abbreviated version.  Please let me know if you need any more detail.
 
* Define an azure function using the trigger above.
* Package it using this Dockerfile:
``` dockerfile
FROM mcr.microsoft.com/azure-functions/node:4-node18

ENV AzureWebJobsScriptRoot=/home/site/wwwroot \
    AzureFunctionsJobHost__Logging__Console__IsEnabled=true

COPY . /home/site/wwwroot
WORKDIR /home/site/wwwroot

RUN chmod 755 commands/*.sh && npm install
```
* Deploy to AKS with an ingress definition similar to this:
``` yaml
kind: Ingress:
metadata:
  annotations:
    kubernetes.io/ingress.class: "nginx"
    cert-manager.io/cluster-issuer: "letsencrypt-production"
spec:
  rules:
    - host: functions.example.net
      paths:
        - path: /runtime/webhooks/blobs
          pathType: Prefix
          backend:
            service:
              name: functions
              port:
                number: 80
  tls:
    - secretName: functions.example.net.cert
      hosts:
        - functions.example.net.net

```
* Define an [Event/Grid trigger pointing at functions.example.net/runtime/webhooks/blobs](https://learn.microsoft.com/en-us/azure/azure-functions/functions-event-grid-blob-trigger?pivots=programming-language-javascript#build-the-endpoint-url) and test it.  It fails with this error: ![Image](https://github.com/user-attachments/assets/eafeec8b-9ec1-40b2-a0f4-a18bfaeb1d9b)

We actually have several functions defined in this deployment.  They all work fine except the EventGrid based blob trigger.  When we had this defined using the more standard blob trigger (which I believe is queue based), it worked, even in this environment, but we had some issues once we reached high volumes and support recommended moving to the EventGrid trigger, which has been working in the App Service environment for some time now.  I just can't figure out where the handler is for that /runtime/webhooks/blobs URL.  If it is part of the Functions Runtime, then it must be at an odd URL locally, or I am missing a setting.

Thanks!
